[package]
name = "posixutils-sh"
version = "0.1.7"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
clap.workspace = true
libc.workspace = true

[[bin]]
name = "sh"
path = "src/main.rs"
