[package]
name = "posixutils-sh"
version = "0.1.7"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
libc.workspace = true
atty = "0.2"

[[bin]]
name = "sh"
path = "main.rs"
