[package]
name = "posixutils-cron"
version = "0.1.0"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
clap = { workspace = true }
libc = { workspace = true }
chrono = { workspace = true }

[[bin]]
name = "crontab"
path = "./src/crontab.rs"

[[bin]]
name = "crond"
path = "./src/crond.rs"