.Dd January 1, 1970
.Dt PROGNAME section
.Os footer text
.Rs
.%O Optional information
.%D January 1, 1970
.%C Location line
.%Q John Doe
.%P pp. 1-100
.%U protocol://path
.%V Volume No. 1
.%N Issue No. 1
.%R Technical report No. 1
.%J Journal Name Line
.%I John Doe
.%B Title Line
.%T Article title line
.%A John Doe
.Re