[package]
name = "posixutils-text"
version = "0.1.10"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
topological-sort = "0.2"
diff = "0.1"
regex.workspace = true
chrono = "0.4"
dirs = "5.0.1"
atty = "0.2.14"
libc = "0.2.155"

[[bin]]
name = "asa"
path = "src/asa.rs"

[[bin]]
name = "comm"
path = "src/comm.rs"

[[bin]]
name = "csplit"
path = "src/csplit.rs"

[[bin]]
name = "diff"
path = "src/diff.rs"

[[bin]]
name = "cut"
path = "src/cut.rs"

[[bin]]
name = "nohup"
path = "src/nohup.rs"

[[bin]]
name = "sort"
path = "src/sort.rs"

[[bin]]
name = "unexpand"
path = "src/unexpand.rs"

[[bin]]
name = "expand"
path = "src/expand.rs"

[[bin]]
name = "fold"
path = "src/fold.rs"

[[bin]]
name = "head"
path = "src/head.rs"

[[bin]]
name = "nl"
path = "src/nl.rs"

[[bin]]
name = "paste"
path = "src/paste.rs"

[[bin]]
name = "pr"
path = "src/pr.rs"

[[bin]]
name = "tsort"
path = "src/tsort.rs"

[[bin]]
name = "wc"
path = "src/wc.rs"

