.Dd $Mdocdate: March 24 2025 $
.Dt TMUX 1
.Os
.Sh AUTHORS
.An Nicholas Marriott Aq Mt nicholas.marriott@gmail.com
.An Nicholas Marriott Aq Mt nicholas.marriott@gmail.com
.An Nicholas Marriott Aq Mt nicholas.marriott@gmail.com
.Sh AUTHORS
.An Mary Ann Horton .
.An Mary Ann Horton .
.An Mary Ann Horton .
.Sh AUTHORS
The Test
program was written by
.An Martijn van Duren Aq Mt martijn@openbsd.org .
.An Martijn van Duren Aq Mt martijn@openbsd.org .
.An Martijn van Duren Aq Mt martijn@openbsd.org .
